export const people = [
  {
    name: "Marcus Cheng",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "Navisworks",
      "BIM Execution Planning",
      "Clash Detection",
      "ACC",
    ],
    email: "marcus.cheng@example.com",
    telephone: "+65-9123-4567",
    imageUrl: "https://randomuser.me/api/portraits/men/21.jpg",
  },
  {
    name: "Elena Tan",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "BIM Coordination",
      "Revit",
      "AutoCAD",
      "IFC",
      "ProjectWise",
    ],
    email: "elena.tan@example.com",
    telephone: "+65-9234-5678",
    imageUrl: "https://randomuser.me/api/portraits/women/28.jpg",
  },
  {
    name: "Samuel Ng",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "Dynamo",
      "Python Scripting",
      "BIM Standards",
      "ACC",
      "ProjectWise",
    ],
    email: "samuel.ng@example.com",
    telephone: "+65-9345-6789",
    imageUrl: "https://randomuser.me/api/portraits/men/32.jpg",
  },
  {
    name: "Lydia Wong",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "Navisworks",
      "Point Cloud Processing",
      "BIM Execution Planning",
      "ProjectWise",
    ],
    email: "lydia.wong@example.com",
    telephone: "+65-9456-7890",
    imageUrl: "https://randomuser.me/api/portraits/women/35.jpg",
  },
  {
    name: "Kenneth Lim",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "BIM 360",
      "MEP Coordination",
      "Clash Detection",
      "ACC",
    ],
    email: "kenneth.lim@example.com",
    telephone: "+65-9567-8901",
    imageUrl: "https://randomuser.me/api/portraits/men/42.jpg",
  },
  {
    name: "Natalie Chia",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "ISO 19650",
      "BIM Execution Planning",
      "AutoCAD",
      "ACC",
    ],
    email: "natalie.chia@example.com",
    telephone: "+65-9678-9012",
    imageUrl: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Terence Yeo",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "Rhino",
      "Grasshopper",
      "Computational BIM",
      "ProjectWise",
    ],
    email: "terence.yeo@example.com",
    telephone: "+65-9789-0123",
    imageUrl: "https://randomuser.me/api/portraits/men/47.jpg",
  },
];
