export const people = [
  {
    name: "Aden Chua Ming Jian",
    company: "Arup Singapore Private Limited",
    companyLogoUrl:
      "https://www.arup.com/~/media/arup/images/logo/arup-logo-red-rgb.svg",
    discipline: "Civil",
    registration_date: "18/10/2016",
    email: "aden.chua@arup.com",
    linkedin: "https://sg.linkedin.com/in/aden-chua-839bab8b",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/54.jpg",
  },
  {
    name: "Adi Prawira Koesoemo Widagdo",
    company: "Eksan Engineering LLP",
    companyLogoUrl:
      "https://www.eksan.com.sg/wp-content/uploads/2024/01/eksan-logo.png",
    discipline: "Civil",
    registration_date: "17/10/2019",
    email: "eksan@eksan.com.sg",
    linkedin: null,
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    name: "Adicitra Sima",
    company: "ByteDance Pte. Ltd.",
    companyLogoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/ByteDance_logo.png",
    discipline: "Electrical",
    registration_date: "23/06/2022",
    email: "adicitrasima@bytedance.com",
    linkedin: "https://sg.linkedin.com/in/adicitrasima",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    name: "Aditya Santoso",
    company: "Land Transport Authority",
    companyLogoUrl:
      "https://www.lta.gov.sg/content/dam/ltaweb/corp-brand/ltalogo.svg",
    discipline: "Mechanical",
    registration_date: "18/10/2018",
    email: "aditya_santoso@lta.gov.sg",
    linkedin:
      "https://sg.linkedin.com/in/aditya-nugraha-santoso-75076758",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Adrain Tan Chuen Kiat",
    company: "AECOM Singapore Pte. Ltd.",
    companyLogoUrl:
      "https://aecom.com/wp-content/uploads/2024/08/AECOM-logo.svg",
    discipline: "Electrical",
    registration_date: "22/11/2012",
    email: "adraintan@hotmail.com",
    linkedin: "https://sg.linkedin.com/in/adrain-tan-09600095",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/86.jpg",
  },
  {
    name: "Adrian Stewart John Billinghurst",
    company: "WSP Consultancy Pte. Ltd.",
    companyLogoUrl:
      "https://www.wsp.com/-/media/images/logos/wsp-logo.svg",
    discipline: "Civil",
    registration_date: "26/01/2007",
    email: "adrian.billinghurst@wsp.com",
    linkedin:
      "https://www.linkedin.com/in/adrian-billinghurst-66241831/",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/25.jpg",
  },
  {
    name: "Afshin Forouzani",
    company: "RBI Singapore Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "21/09/2004",
    email: "mosab.alabdulkarim@aecom.com",
    linkedin: null,
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    name: "Agung Rinaldi Santoso",
    company: "AECOM Singapore Pte. Ltd.",
    companyLogoUrl:
      "https://aecom.com/wp-content/uploads/2024/08/AECOM-logo.svg",
    discipline: "Civil",
    registration_date: "19/09/2019",
    email: "agung.rinaldi.s@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/agung-rinaldi-santoso-76411012b/",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/96.jpg",
  },
  {
    name: "Agus Riatono",
    company: "Land Transport Authority",
    companyLogoUrl:
      "https://www.lta.gov.sg/content/dam/ltaweb/corp-brand/ltalogo.svg",
    discipline: "Civil",
    registration_date: "16/05/2006",
    email: "agusriatono@gmail.com",
    linkedin: "https://www.linkedin.com/in/agus-riatono-6b3030198",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/64.jpg",
  },
  {
    name: "Ahmad Amirul Hakim Bin 'A'lauddin",
    company: "SP PowerGrid Limited",
    companyLogoUrl:
      "https://upload.wikimedia.org/wikipedia/commons/7/75/SP_Group_logo.svg",
    discipline: "Electrical",
    registration_date: "25/01/2024",
    email: "ahmadamirul@spgroup.com.sg",
    linkedin: "http://linkedin.com/in/ahmadamirulhakim/",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/51.jpg",
  },
  {
    name: "Ahmad Dani Bin Sulaiman",
    company: "SHELL Singapore Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Chemical",
    registration_date: "18/11/2017",
    email: "ahmad.sulaiman@shell.com",
    linkedin: "https://sg.linkedin.com/in/ahmaddanisulaiman",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/68.jpg",
  },
  {
    name: "Ahmad Nadim Bin Zainal",
    company: "Building and Construction Authority",
    companyLogoUrl:
      "https://www1.bca.gov.sg/assets/Uploads/BCA-logo.png",
    discipline: "Electrical",
    registration_date: "18/10/2018",
    email: "ahmad_nadim@bca.gov.sg",
    linkedin: "https://sg.linkedin.com/in/ahmad-nadim-2b210463",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/95.jpg",
  },
  {
    name: "Alex Leong Wai Mun",
    company: "SP Group",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "18/10/2018",
    email: "alexander@ncs.com.sg",
    linkedin:
      "https://sg.linkedin.com/in/alex-leong-kam-wei-45b960170",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/61.jpg",
  },
  {
    name: "Allan Tay Eng Mian",
    company: "Mott MacDonald Singapore Pte Limited",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "17/09/2020",
    email: "allan.tay@mottmac.com",
    linkedin: "http://linkedin.com/in/allan-tay-38132b1a6/",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/97.jpg",
  },
  {
    name: "Alvin Ong Thiam Heng",
    company: "HPX Consulting Engineers Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Mechanical",
    registration_date: "24/10/2024",
    email: "xaal44@gmail.com",
    linkedin:
      "https://www.linkedin.com/in/alvin-ong-sg/?originalSubdomain=sg",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/72.jpg",
  },
  {
    name: "Anastasia Maria Santoso",
    company: "Building and Construction Authority",
    companyLogoUrl:
      "https://www1.bca.gov.sg/assets/Uploads/BCA-logo.png",
    discipline: "Civil",
    registration_date: "18/10/2018",
    email: "anastasiasantoso@gmail.com",
    linkedin: "https://sg.linkedin.com/in/anastasia-santoso-a6444691",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/48.jpg",
  },
  {
    name: "Andra Wiedyanto Thedy",
    company: "Marina Bay Sands Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "22/05/2017",
    email: "andra.thedy@marinabaysands.com",
    linkedin: "https://www.linkedin.com/in/andrathedy/",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/50.jpg",
  },
  {
    name: "Andreas Tumengan",
    company: "Surbana Jurong Consultants Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "04/04/1984",
    email: "andreas.indrakusuma@surbanajurong.com",
    linkedin: "https://sg.linkedin.com/in/and23as",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    name: "Andrew Tay Kim Tat",
    company: "Perita Electrical Engineering Pte Ltd",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "14/12/2018",
    email: "andrew.tay@perita.com.sg",
    linkedin: "https://sg.linkedin.com/in/andrew-tay-56b122206",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/86.jpg",
  },
  {
    name: "Andy Ng Yao Hong",
    company: "Ministry of Home Affairs",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "22/05/2025",
    email: "andy.ng@arctera.io",
    linkedin: "https://sg.linkedin.com/in/andy-ng-107343",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/76.jpg",
  },
  {
    name: "Andy Teng Kuang Yong",
    company: "WSP Consultancy Pte. Ltd.",
    companyLogoUrl:
      "https://www.wsp.com/-/media/images/logos/wsp-logo.svg",
    discipline: "Civil",
    registration_date: "19/09/2017",
    email: "andy.teng@lcrecer.com",
    linkedin: "https://sg.linkedin.com/in/andy-teng-41a6441",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/91.jpg",
  },
  {
    name: "Ang Boon Kian",
    company: "Ramboll Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "19/05/1993",
    email: "boon.a@starhub.com",
    linkedin: "https://sg.linkedin.com/in/boon-kian-a-0900671aa",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    name: "Ang Boon Wee",
    company: "HDR Consulting Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Mechanical",
    registration_date: "15/10/2020",
    email: "bang@hdrinc.com",
    linkedin: "https://sg.linkedin.com/in/boon-wee-ang",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/99.jpg",
  },
  {
    name: "Ang Chee Keong",
    company: "Singapore District Cooling Pte Ltd",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "21/06/2005",
    email: "angkeong@spgroup.com.sg",
    linkedin: "https://sg.linkedin.com/in/ang-chee-keong-40514765",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/95.jpg",
  },
  {
    name: "Ang Cheng Hua",
    company: "Surbana Jurong Consultants Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Mechanical",
    registration_date: "22/09/2016",
    email: "aaronang@hotmail.com",
    linkedin: "https://www.linkedin.com/in/ang-cheng-hua-9378887a",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    name: "Ang Chong Lee",
    company: "Zemag Engineering Pte Ltd",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "20/09/1989",
    email: "chong.ang@scjohnson.com",
    linkedin: "https://sg.linkedin.com/in/chongleeang",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    name: "Ang Choon Keat",
    company: "Prostruct Consulting Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "18/02/2010",
    email: "echo.pmc@me.com",
    linkedin: "https://sg.linkedin.com/in/choon-keat-ang-0581b147",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    name: "Ang Chye Heng",
    company: "VEngineers Consultancy Pte Ltd",
    companyLogoUrl: null,
    discipline: "Civil",
    registration_date: "15/03/2007",
    email: "achch53@gmail.com",
    linkedin: null,
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/87.jpg",
  },
  {
    name: "Ang Eng Chuan",
    company: "K L Au Consultants Pte. Ltd.",
    companyLogoUrl: null,
    discipline: "Mechanical",
    registration_date: "28/10/2003",
    email: "roy.ang@klau.com.sg",
    linkedin: "https://sg.linkedin.com/in/roy-ang-b796ba89",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/men/63.jpg",
  },
  {
    name: "Ang Kah Eng",
    company: "Microsoft Operations Pte Ltd",
    companyLogoUrl: null,
    discipline: "Electrical",
    registration_date: "21/09/2015",
    email: "the_endless_waltz@hotmail.com",
    linkedin: "https://sg.linkedin.com/in/angkaheng",
    title: "Engineer",
    role: "User",
    skills: ["Revit", "Fire Protection"],
    telephone: "",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
];
