export const people = [
  {
    name: "John Reeves",
    title: "Structural Engineer",
    role: "User",
    skills: ["Tekla", "AutoCAD", "Revit", "Structural"],
    email: "john.tan@example.com",
    telephone: "+65-9876-5432",
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    name: "Benigno Baltazar",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "BIM Execution Planning",
      "AutoCAD",
      "BIM Manager",
      "Structural Analysis",
    ],
    email: "matthew.goh@example.com",
    telephone: "+65-9644-8899",
    imageUrl: "/ben.jpeg",
  },
  {
    name: "Sarah Lim",
    title: "Electrical Engineer",
    role: "User",
    skills: ["Electrical", "Revit", "AutoCAD"],
    email: "sarah.lim@example.com",
    telephone: "+65-9456-7890",
    imageUrl: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    name: "Daniel Wong",
    title: "Offshore Engineer",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD", "Piping"],
    email: "daniel.wong@example.com",
    telephone: "+65-9567-8901",
    imageUrl: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    name: "Rachel Tan",
    title: "BIM Modeler",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD"],
    email: "rachel.tan@example.com",
    telephone: "+65-9111-2233",
    imageUrl: "https://randomuser.me/api/portraits/women/43.jpg",
  },
  {
    name: "Adrian Foo",
    title: "Power Systems Engineer",
    role: "Admin",
    skills: ["Revit", "Electrical", "AutoCAD"],
    email: "adrian.foo@example.com",
    telephone: "+65-9422-6677",
    imageUrl: "https://randomuser.me/api/portraits/men/46.jpg",
  },
  {
    name: "Lucas Teo",
    title: "BIM Specialist",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD"],
    email: "lucas.teo@example.com",
    telephone: "+65-9866-1011",
    imageUrl: "https://randomuser.me/api/portraits/men/50.jpg",
  },
];
