/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://e6w5r6d6iraxfimpxr63egezpq.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-a6udnhpsmbeyrhf4ntr3tbsthe",
    "aws_cognito_identity_pool_id": "ap-southeast-1:38206704-ddb6-46a7-8561-3a0010ee5f64",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_AqL6LlA0n",
    "aws_user_pools_web_client_id": "3et5v4bc7cfecgaebrmnltkvql",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "ap-southeast-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "User-jfplwny5vvewtpn7f3utjsemp4-production",
            "region": "ap-southeast-1"
        }
    ],
    "aws_user_files_s3_bucket": "acegroup-webdam",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
