export const people = [
  {
    name: "Jane Lee",
    title: "BIM Coordinator",
    role: "Admin",
    skills: ["Revit", "Plumbing", "Sanitary", "Fire Protection"],
    email: "jane.lee@example.com",
    telephone: "+65-9123-4567",
    imageUrl: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    name: "John Reeves",
    title: "Structural Engineer",
    role: "User",
    skills: ["Tekla", "AutoCAD", "Revit", "Structural"],
    email: "john.tan@example.com",
    telephone: "+65-9876-5432",
    imageUrl: "https://randomuser.me/api/portraits/men/36.jpg",
  },
  {
    name: "Benigno Baltazar",
    title: "BIM Manager",
    role: "Admin",
    skills: [
      "Revit",
      "BIM Execution Planning",
      "AutoCAD",
      "BIM Manager",
      "Structural Analysis",
    ],
    email: "matthew.goh@example.com",
    telephone: "+65-9644-8899",
    imageUrl: "/ben.jpeg",
  },
  {
    name: "Emily Wong",
    title: "Architect",
    role: "Editor",
    skills: ["Archicad", "Revit", "OpenBuildings"],
    email: "emily.wong@example.com",
    telephone: "+65-9234-5678",
    imageUrl: "https://randomuser.me/api/portraits/women/37.jpg",
  },
  {
    name: "Mark Jacobs",
    title: "MEP Engineer",
    role: "Admin",
    skills: ["Revit", "Fire Protection", "Piping", "Plumbing"],
    email: "michael.cheng@example.com",
    telephone: "+65-9345-6789",
    imageUrl: "https://randomuser.me/api/portraits/men/38.jpg",
  },
  {
    name: "Sarah Lim",
    title: "Electrical Engineer",
    role: "User",
    skills: ["Electrical", "Revit", "AutoCAD"],
    email: "sarah.lim@example.com",
    telephone: "+65-9456-7890",
    imageUrl: "https://randomuser.me/api/portraits/women/39.jpg",
  },
  {
    name: "Daniel Wong",
    title: "Offshore Engineer",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD", "Piping"],
    email: "daniel.wong@example.com",
    telephone: "+65-9567-8901",
    imageUrl: "https://randomuser.me/api/portraits/men/40.jpg",
  },
  {
    name: "Rachel Tan",
    title: "BIM Modeler",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD"],
    email: "rachel.tan@example.com",
    telephone: "+65-9111-2233",
    imageUrl: "https://randomuser.me/api/portraits/women/43.jpg",
  },
  {
    name: "Kevin Ng",
    title: "Mechanical Engineer",
    role: "Admin",
    skills: ["Revit", "Piping", "Plumbing"],
    email: "kevin.ng@example.com",
    telephone: "+65-9222-3344",
    imageUrl: "https://randomuser.me/api/portraits/men/44.jpg",
  },
  {
    name: "Tiffany",
    title: "Structural BIM Consultant",
    role: "Editor",
    skills: ["Revit", "Tekla", "Structural"],
    email: "tiffany.chang@example.com",
    telephone: "+65-9311-5566",
    imageUrl: "https://randomuser.me/api/portraits/women/45.jpg",
  },
  {
    name: "Adrian Foo",
    title: "Power Systems Engineer",
    role: "Admin",
    skills: ["Revit", "Electrical", "AutoCAD"],
    email: "adrian.foo@example.com",
    telephone: "+65-9422-6677",
    imageUrl: "https://randomuser.me/api/portraits/men/46.jpg",
  },

  {
    name: "Lucas Teo",
    title: "BIM Specialist",
    role: "User",
    skills: ["Revit", "Tekla", "AutoCAD"],
    email: "lucas.teo@example.com",
    telephone: "+65-9866-1011",
    imageUrl: "https://randomuser.me/api/portraits/men/50.jpg",
  },
];
